# Test generated by RoostGPT for test roostPostmanTest using AI Type Azure Open AI and AI Model roost-gpt4-32k

# RoostTestHash=74f49e1ef7

config:
  target: "{{ $processEnvironment.API_HOST }}"
  plugins:
    expect: {}
  payload:
    path: "./order_orderId_get_others.csv"
    fields:
      - "orderId"
    skipHeader: true
  processor: "./my-script.js"
scenarios:
  - name: "Test unsuccessfull conditions for API /store/order/{orderId}"
    flow:
      - get:
          url: "/store/order/{{ orderId }}"
          headers:
            Authorization: "{{ $processEnvironment.AUTH_TOKEN }}"
          expect:
            - statusCode: 400
            - hasProperty: "message"
            - equals: 
                message: "Invalid ID supplied"
          log: "1st case: testing with invalid orderId. Expected status Code: 400, with error message 'Invalid ID supplied'"
      - think: 1
      - get:
          url: "/store/order/{{ orderId }}"
          headers:
            Authorization: "{{ $processEnvironment.AUTH_TOKEN }}"
          expect:
            - statusCode: 404
            - hasProperty: "message"
            - equals: 
                message: "Order not found"
          log: "2nd case: testing with valid orderId, which does not exist in the db. Expected status Code: 404, with error message 'Order not found'"
      - think: 1
      - get:
          url: "/invalidUrl/{{ orderId }}"
          headers:
            Authorization: "{{ $processEnvironment.AUTH_TOKEN }}"
          expect:
            - statusCode: 404
            - hasProperty: "message"
            - equals: 
                message: "Resource not found"
          log: "3rd case: testing with invalid url. Expected status Code: 404, with error message 'Resource not found'"
      - think: 1
      - get:
          url: "/store/order/{{ orderId }}"
          headers:
            Authorization: "invalidToken"
          expect:
            - statusCode: 403
            - hasProperty: "message"
            - equals: 
                message: "Forbidden. Invalid Authentication token"
          log: "4th case: testing with invalid authToken. Expected status Code: 403, with error message 'Forbidden. Invalid Authentication token'"
